### ISSUE TITLE
PlatformException (PlatformException(PERMISSION_DENIED, null, null))

### ISSUE THREAD

**Issue by yhhCh405** [flutter-moum/flutter_sim_info#15]
Although READ_PHONE_STATE permission was added, these exception was still caught.

**Comment by ajaqueira** [comment]
Any solution yet? I'm having the same problem.

**Comment by rionaldi1** [comment]
> Although READ_PHONE_STATE permission was added, these exception was still caught.

you have to ask permission too, don't just add the permission.

**Comment by yhhCh405** [comment]
That's my silly mistake xD.  I forgot to ask permission.

**Comment by thanhbinh84** [comment]
@YKW93 @rionaldi1 I checked android code, none of our functions needs READ_PHONE_STATE, why do we need this very sensible permission?

https://developer.android.com/reference/android/telephony/TelephonyManager#getSimCountryIso()
https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkOperatorName()
https://developer.android.com/reference/android/telephony/TelephonyManager#getSimState()
https://developer.android.com/reference/android/telephony/TelephonyManager#getSimOperator()

**Comment by thanhbinh84** [comment]
Please check if we really need READ_PHONE_STATE permssion
