### ISSUE TITLE
Do we really need READ_PHONE_STATE permission?

### ISSUE THREAD

**Issue by thanhbinh84** [flutter-moum/flutter_sim_info#16]
I checked android code, none of our functions needs READ_PHONE_STATE, why do we need this very sensible permission?

https://developer.android.com/reference/android/telephony/TelephonyManager#getSimCountryIso()
https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkOperatorName()
https://developer.android.com/reference/android/telephony/TelephonyManager#getSimState()
https://developer.android.com/reference/android/telephony/TelephonyManager#getSimOperator()

**Comment by Faiyyaz** [comment]
I don't think so i read the docs and tried TelephonyManager.getSimCountryIso() and it is working fine!

**Comment by thanhbinh84** [comment]
@Faiyyaz it is working fine without 'READ_PHONE_STATE' permission right? Why do you say 'I don't think so'?

**Comment by Faiyyaz** [comment]
I said I don't think so because I just tried one method which I want I didn't tried every method available with the plugin

**Comment by thanhbinh84** [comment]
Ah, I see, so you agree with me that we don't need 'READ_PHONE_STATE' permission. I thought you disagreed :D

**Comment by Faiyyaz** [comment]
Yes. I have forked and made a PR request you can clone it and see

**Comment by songyiYu** [comment]
Fixed!
